<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-08-30T18:36:17 IST" name="Page Object test example" finished-at="2024-08-30T18:36:20 IST" duration-ms="3703">
    <groups>
    </groups>
    <test started-at="2024-08-30T18:36:17 IST" name="Login with valid " finished-at="2024-08-30T18:36:20 IST" duration-ms="3703">
      <class name="test.DashboardTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:test.DashboardTest@158da8e]" started-at="2024-08-30T18:36:10 IST" name="setup" finished-at="2024-08-30T18:36:17 IST" duration-ms="6771" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method is-config="true" signature="init()[pri:0, instance:test.DashboardTest@158da8e]" started-at="2024-08-30T18:36:17 IST" name="init" finished-at="2024-08-30T18:36:17 IST" duration-ms="5" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method signature="setlogin()[pri:0, instance:test.DashboardTest@158da8e]" started-at="2024-08-30T18:36:17 IST" name="setlogin" finished-at="2024-08-30T18:36:20 IST" duration-ms="3507" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setlogin -->
        <test-method is-config="true" signature="init()[pri:0, instance:test.DashboardTest@158da8e]" started-at="2024-08-30T18:36:20 IST" name="init" finished-at="2024-08-30T18:36:20 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method signature="sideNavTxtMatch()[pri:0, instance:test.DashboardTest@158da8e]" started-at="2024-08-30T18:36:20 IST" name="sideNavTxtMatch" finished-at="2024-08-30T18:36:20 IST" duration-ms="105" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Announcements] but found [Dashboard]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Announcements] but found [Dashboard]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at test.DashboardTest.sideNavTxtMatch(DashboardTest.java:214)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sideNavTxtMatch -->
        <test-method is-config="true" signature="close()[pri:0, instance:test.DashboardTest@158da8e]" started-at="2024-08-30T18:36:20 IST" name="close" finished-at="2024-08-30T18:36:22 IST" duration-ms="1724" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- test.DashboardTest -->
    </test> <!-- Login with valid  -->
  </suite> <!-- Page Object test example -->
</testng-results>
